### ISSUE TITLE
Host Based Authentication Configuration Issue

### ISSUE THREAD

**Issue by naresh3591** [crate/crate-jdbc#230]
Hi All,

This is my crate.yml configuration for host based authentication to restrict connections to CrateDB only from certain IP Addresses (here in this case 10.10.10.111):
```
auth:
  host_based:
    enabled: true
    config:
      0:
        user: crate
      a:
        user: naresh
        address: 127.0.0.1
        method: trust
     b:
        user: naresh
        address: 10.10.10.111
        method: trust
```

Using below code from a stand-alone java application I am able to connect to CrateDB.

```
Connection con = DriverManager.getConnection(
                    String.format(Locale.ENGLISH, "jdbc:crate://%s:%d/?user=naresh", "localhost", 5434));
```

Using below code from a stand-alone java application with IP address,
```
Connection con = DriverManager.getConnection(
                    String.format(Locale.ENGLISH, "jdbc:crate://%s:%d/?user=naresh", "10.10.10.111", 5434));
```
 I am getting following error while connecting to CrateDB:

io.crate.shade.org.postgresql.util.PSQLException: Connection to 10.10.10.111:5434 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Can someone help me with the crate configuration for host based authentication.
